// Generated by CoffeeScript 1.6.2
var ShareJS, ShareJSOpts, connect, port, server;

connect = require('connect');

ShareJS = require('share').server;

ShareJSOpts = {
  browserChannel: {
    cors: "*"
  },
  db: "none"
};

server = connect.createServer();

server.use(connect['static'](__dirname + "/static"));

ShareJS.attach(server, ShareJSOpts);

port = process.env.OPENSHIFT_INTERNAL_PORT || 5000;
ip = process.env.OPENSHIFT_INTERNAL_IP || '127.0.0.1';

server.listen(port, ip, function() {
  return console.log("Listening on " + port);
});
